services:
  db:
    image: postgres:16
    container_name: fastapi_ai_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_ai

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d fastapi_ai" ]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_ai_app
    restart: unless-stopped

    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000"

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/fastapi_ai
      OLLAMA_URL: http://host.docker.internal:11434/api/generate
      OLLAMA_MODEL: qwen2.5:3b

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/')"

        ]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: fastapi_ai_prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: fastapi_ai_grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus


volumes:
  postgres_data: